export default [
  {
    id: 1,
    description: "Fetch the list of all employees with filters",
    module: "Employee Management",
    method: "GET",
    path: "/employees/fetch-list",
    cache: 0,
    active: true,
    code: "const data = [{ name: 'John Doe', position: 'Developer' }, { name: 'Jane Smith', position: 'Designer' }]; return { status: 200, data };",
  },
  {
    id: 2,
    description: "Fetch details of a specific employee by ID",
    module: "Employee Management",
    method: "GET",
    path: "/employees/fetch-details",
    cache: 0,
    active: true,
    code: "const data = { name: req.query.name, position: req.query.position }; return { status: 200, data };",
  },
  {
    id: 3,
    description: "Create a new employee",
    module: "Employee Management",
    method: "POST",
    path: "/employees/create",
    cache: 0,
    active: true,
    code: "return { status: 501, data: { message: 'Not Implemented' } };",
  },
  {
    id: 4,
    description: "Update employee details",
    module: "Employee Management",
    method: "POST",
    path: "/employees/update",
    cache: 0,
    active: true,
    code: "return { status: 501, data: { message: 'Not Implemented' } };",
  },
  {
    id: 5,
    description: "Delete an employee",
    module: "Employee Management",
    method: "POST",
    path: "/employees/delete",
    cache: 0,
    active: true,
    code: "return { status: 501, data: { message: 'Not Implemented' } };",
  },
];
