export default [
  {
    id: 1,
    description: "Fetch the list of all employees with filters",
    module: "Employee Management",
    method: "GET",
    route: "/employees/fetch-list",
    cache: 0,
    active: true,
    code: "return",
  },
  {
    id: 2,
    description: "Fetch details of a specific employee by ID",
    module: "Employee Management",
    method: "GET",
    route: "/employees/fetch-details",
    cache: 0,
    active: true,
  },
  {
    id: 3,
    description: "Create a new employee",
    module: "Employee Management",
    method: "POST",
    route: "/employees/create",
    cache: 0,
    active: true,
  },
  {
    id: 4,
    description: "Update employee details",
    module: "Employee Management",
    method: "POST",
    route: "/employees/update",
    cache: 0,
    active: true,
  },
  {
    id: 5,
    description: "Delete an employee",
    module: "Employee Management",
    method: "POST",
    route: "/employees/delete",
    cache: 0,
    active: true,
  },
];
