export default [
  {
    id: 1,
    description: "Fetch the list of all employees with filters",
    module: "Employee Management",
    method: "GET",
    path: "/employees/fetch-list",
    cache: 0,
    active: true,
    code: "const test = { name: 'John Doe', position: 'Developer' }; return { status: 200, data: test };",
  },
  {
    id: 2,
    description: "Fetch details of a specific employee by ID",
    module: "Employee Management",
    method: "GET",
    path: "/employees/fetch-details",
    cache: 0,
    active: true,
    code: "DEF456",
  },
  {
    id: 3,
    description: "Create a new employee",
    module: "Employee Management",
    method: "POST",
    path: "/employees/create",
    cache: 0,
    active: true,
    code: "GHI789",
  },
  {
    id: 4,
    description: "Update employee details",
    module: "Employee Management",
    method: "POST",
    path: "/employees/update",
    cache: 0,
    active: true,
    code: "JKL012",
  },
  {
    id: 5,
    description: "Delete an employee",
    module: "Employee Management",
    method: "POST",
    path: "/employees/delete",
    cache: 0,
    active: true,
    code: "MNO345",
  },
];
